version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    registries:
      - public-npm

registries:
  public-npm:
    type: "npm-registry"
    url: "https://registry.npmjs.org"
    token: ${{ secrets.DUMMY_NPM_TOKEN }}
    replaces-base: true
